stages:
  - test
  - build
  - push

variables:
  DOCKER_IMAGE_NAME: "my-latest-container"
  DOCKER_IMAGE_TAG: latest

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    # Restore dependencies and build the test project #
    - ls -R  # List all files and directories recursively #
    - dotnet restore ./TestProject1/TestProject1.csproj
    - dotnet build ./TestProject1/TestProject1.csproj

    # Run XUnit tests
    - dotnet test ./TestProject1/TestProject1.csproj

  only:
    - main

build:
  image: docker:stable
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main

push:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main

